name: Build and Push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gh-actions-docker-02:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/gh-actions-docker-02:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/gh-actions-docker-02:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gh-actions-docker-02:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gh-actions-docker-02:latest
